module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#001a41',
        'on-secondary': '#333023',
        'secondary-container': '#4a4738',
        'on-tertiary-fixed-variant': '#304671',
        'surface': '#061612',
        'error': '#ffb4ab',
        'on-secondary-fixed': '#1e1c10',
        'primary-fixed-dim': '#e9c176',
        'tertiary': '#b0c6f9',
        'inverse-on-surface': '#24342e',
        'on-error-container': '#ffdad6',
        'on-tertiary-container': '#233a65',
        'surface-container': '#13231e',
        'error-container': '#93000a',
        'inverse-primary': '#775a19',
        'surface-tint': '#e9c176',
        'secondary-fixed': '#e9e2cf',
        'surface-container-low': '#0f1f1a',
        'primary': '#e9c176',
        'on-error': '#690005',
        'surface-variant': '#283833',
        'secondary': '#ccc6b3',
        'primary-container': '#c5a059',
        'surface-container-highest': '#283833',
        'on-primary-fixed': '#261900',
        'surface-bright': '#2c3c37',
        'surface-container-high': '#1d2d28',
        'tertiary-fixed': '#d8e2ff',
        'background': '#061612',
        'on-background': '#d4e7df',
        'outline': '#9a8f80',
        'on-surface-variant': '#d1c5b4',
        'surface-container-lowest': '#03110d',
        'on-secondary-fixed-variant': '#4a4738',
        'on-primary-fixed-variant': '#5d4201',
        'on-secondary-container': '#bbb5a3',
        'primary-fixed': '#ffdea5',
        'surface-dim': '#061612',
        'secondary-fixed-dim': '#ccc6b3',
        'on-surface': '#d4e7df',
        'inverse-surface': '#d4e7df',
        'tertiary-container': '#8fa5d6',
        'outline-variant': '#4e4639',
        'on-primary-container': '#4e3700',
        'on-primary': '#412d00',
        'tertiary-fixed-dim': '#b0c6f9',
        'on-tertiary': '#173059',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['"Newsreader"', 'serif'],
        body: ['"Manrope"', 'sans-serif'],
        label: ['"Manrope"', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
